✨  Change Icon color inside PlanCard
Gympass/yoga pull request #313
Opened 2021-08-18 18:16 UTC by mmartinsoliveira

[jira-task]: https://gympass.atlassian.net/browse/CODEME-184
[jira-img]: https://img.shields.io/badge/issue-JIRA-blue.svg

<center>

[![JIRA][jira-img]][jira-task]

</center>

# ✨ Change Icon color inside PlanCard

| before | after |
|------- |------| 
| ![image](https://user-images.githubusercontent.com/46993493/129949580-90638c1f-b35a-4015-860c-78c177c83853.png) | ![image](https://user-images.githubusercontent.com/46993493/129949472-fd222d18-5fcb-4a30-9ba2-53cd87046787.png)  |

2021-08-18 18:21 UTC, marcosricardo approved these changes

2021-08-18 21:35 UTC, ericcleao approved these changes

2021-08-18 23:39 UTC, alycecristines approved these changes

2021-08-19 11:29 UTC, ggdaltoso requested changes

2021-08-19 11:29 UTC, ggdaltoso commented on packages/yoga/src/Card/native/PlanCard/List.jsx
> +                fill={yogaTheme.yoga.colors.secondary}
I think it would make more sense if we fill the icon with the same color as its next text (`yogaTheme.yoga.colors.text.primary`). What do you think?

2021-08-19 12:15 UTC, ggdaltoso approved these changes

2021-08-19 12:15 UTC, merged