Elevation. Revisited.
Gympass/yoga pull request #318
Opened 2021-08-23 18:59 UTC by ggdaltoso

# Breaking change
It isn't 😄 

Our elevation system has never worked as expected on Android devices. We always needed to add `elevation` and `box-shadow` to the component and try to figure out how shadow it would generate on iOS and Android as well.

This PR changes our tokens, adding the specifics for each platform.

### Web

| Before | After |
| ------ | ----- |
| ![image](https://user-images.githubusercontent.com/6536985/130500263-7fc7de44-8b2d-44a5-b8de-5748b05d3c11.png) | ![image](https://user-images.githubusercontent.com/6536985/130500290-186a5787-7634-4f1d-ab1a-df10212f5d8e.png) |

### Android

![image](https://user-images.githubusercontent.com/6536985/130501340-b841c5e8-476e-4de4-ab97-b56fb3e44f18.png)

### iOS

![image](https://user-images.githubusercontent.com/6536985/130501376-e491356f-7a43-4572-a616-3078eb80397a.png)

It is important to say that those changes on our system will be reflected in our Box component, making it possible to use the same code to add our shadows to a component:

| Code | Web | Android | iOS |
| ----- | ----- | -------- | --- |
| ![image](https://user-images.githubusercontent.com/6536985/130502153-052eb4c3-9b7a-48bd-a1af-3818b26e97bf.png) | ![image](https://user-images.githubusercontent.com/6536985/130502265-5463b21a-c986-4335-bbb0-bc31d2fa13cc.png) | ![image](https://user-images.githubusercontent.com/6536985/130502347-f3c759fb-5c9d-4930-969b-4272d6a68f50.png) | ![image](https://user-images.githubusercontent.com/6536985/130502380-65a84c73-f3aa-4a1b-8a87-2ef9e8683039.png) |

2021-08-23 20:33 UTC, tcK1 requested changes
Instead of using the `.attrs()` method, what do you think of this approach:

```jsx
// Using the card element as an example

<Box elevation="components.card.elevation" {...props} />
```

Would it work? This can be used a lot on this PR. 🤔 

-------

It seems like we are passing props directly to the `View` component in some cases. I've marked a single occurrence as an example, but there are many on this PR. We should find where we are doing it and fix it.

2021-08-23 20:33 UTC, tcK1 commented on packages/yoga/src/Card/native/PlanCard/__snapshots__/PlanCard.test.jsx.snap
> +      pt={16}
🕵🏼

2021-08-23 21:14 UTC, andreloureiro approved these changes

2021-08-24 14:23 UTC, coelhucas approved these changes

2021-08-24 17:08 UTC, ggdaltoso commented
Good point, @tcK1 

For the first, your suggestion wouldn't work because our system matches each prop to its respective prop on `theme`. For example:

This works because we have a color, on our theme, matching `feedback.success.dark` 

<table>
<tr>
<td>

  ```jsx
<>
    <Box color="feedback.success.light" />  
    <Box bgColor="feedback.success.dark" />  
</>
```
</td>
<td>

  ```js
theme: {
    yoga: {
      colors: {
        success: {
          light: "#C1EEDB"
          dark: "#1D856C"
        }
      },
    }
}
```
</td>
</tr>
</table>

So, with this in mind, we don't match the entire theme to the prop itself. Just the respective ones. And this is why your code wouldn't work:




<table>
<tr>
<td>

```jsx
// Using the card element as an example
<Box elevation="components.card.elevation" {...props} />
```
</td>
<td>

  ```js
theme: {
    yoga: {
      elevations: {
        0: "none"
        1: "0 2px 6px rgba(152, 152, 166, 0.25)",
        2: "0 4px 12px rgba(152, 152, 166, 0.25)",
        3: "0 8px 20px rgba(152, 152, 166, 0.25)",
        zero: "none",
        small: "0 2px 6px rgba(152, 152, 166, 0.25)",
        medium: "0 4px 12px rgba(152, 152, 166, 0.25)",
        large: "0 8px 20px rgba(152, 152, 166, 0.25)",
      }
    }
}
```
</td>
</tr>
</table>

You are trying to match the elevation prop to the components but our system will try to resolve it as an elevation and it would not find the respective.

2021-08-25 13:15 UTC, ggdaltoso commented
> Secondly, it seems like we are passing props directly to the `View` component in some cases. I've marked a single occurrence as an example, but there are many on this PR. We should find where we are doing it and fix it.

For this second point, I think it is a [styled-components issue](https://github.com/styled-components/styled-components/issues/135) that has been solved (?) in v5 with [shouldforwardprop](https://styled-components.com/docs/api#shouldforwardprop) and it could be revisited when we bump SC version. Is it good for you, @tcK1 ?

2021-08-25 13:17 UTC, tcK1 commented
> Is it good for you, @tcK1 ?

Okay!

2021-08-25 13:17 UTC, tcK1 approved these changes

2021-08-25 13:46 UTC, alycecristines approved these changes

2021-08-25 13:59 UTC, merged