Refactor/input legend
Gympass/yoga pull request #387
Opened 2021-11-05 18:30 UTC by coelhucas

This intend to remove the "magical" `1000px` width for the legend tag that prevents the input border from overlapping the input label layout (example below)

![image](https://user-images.githubusercontent.com/28108272/140560860-bafc1a6d-18a3-4b87-a9f7-8b3318d1510c.png)

The update keeps the current behavior of it. We should look forward the future to replace this workaround (kinda gambiarra) with some proper way of preventing it.

https://user-images.githubusercontent.com/28108272/140560003-a274b3bf-e605-4b49-afa2-a0cd8a8e698c.mp4

2021-11-05 19:16 UTC, frgiovanna approved these changes

2021-11-08 10:37 UTC, ericcleao approved these changes

2021-11-08 10:59 UTC, mmartinsoliveira approved these changes

2021-11-08 11:29 UTC, ggdaltoso requested changes
There is no support in IE

![image](https://user-images.githubusercontent.com/6536985/140734467-bffe82fa-b6de-4e36-bf17-0deac8e361ec.png)

2021-11-08 11:35 UTC, coelhucas commented
Are we supposed to support IE, though?

2021-11-08 16:25 UTC, ggdaltoso approved these changes

2021-11-08 16:33 UTC, merged