🚀 feat(components): add center props to feedback component
gympass/yoga pull request #610
Opened 2023-01-20 14:41 UTC by luanlorenzo

[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-550)

## Description 📄

Add the `center` props to the `Feedback` component to allow the usage in a context where doesn't need to be vertically centered.

## Platforms 📲

- [x] Web
- [ ] Mobile

## Type of change 🔍

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? 🧪

- [ ] Unit Test
- [x] Snapshot Test

## Checklist: 🔍

- [x] My code follows the contribution guide of this project [Contributing Guide](https://github.com/Gympass/yoga/blob/master/CONTRIBUTING.md)
- [x] Layout matches design prototype: [FIGMA](https://figma.com/file/YOUR_LINK)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Screenshots 📸

**Example of usage with additional content**
<img width="597" alt="image" src="https://user-images.githubusercontent.com/18699514/213725596-ebc92f28-50e0-4943-9f3e-5d660aec48bb.png">

2023-01-20 17:38 UTC, guilhermecardoso-gympass requested changes
Use the Yoga Tokens sizes and spacing for sizes of your code.! Example

font-size: 16px you can change for: font-size: ${fontSizes.small}px;

for access that properti you can import from Yoga  theme:

${({
    theme: {
      yoga: { fontWeights, colors, lineHeights, spacing, fontSizes },
    },
  }) => `

2023-01-20 18:12 UTC, luanlorenzo commented
> Use the Yoga Tokens sizes and spacing for sizes of your code.! Example
> 
> font-size: 16px you can change for: font-size: ${fontSizes.small}px;
> 
> for access that properti you can import from Yoga theme:
> 
> ${({ theme: { yoga: { fontWeights, colors, lineHeights, spacing, fontSizes }, }, }) => `

hey @guilhermecardoso-gympass! the properties that you are talking about were generated by the snapshot test. The style definitions are using the tokens correctly. could you check again if I'm missing at some point?

2023-01-23 18:07 UTC, guilhermecardoso-gympass approved these changes

2023-01-23 18:07 UTC, merged

2023-03-28 17:44 UTC, matheushdsbr commented
@all-contributors please add @luanlorenzo for code and doc