feat(tag): 🚀 add new prop ellipsis for large texts on tag
gympass/yoga pull request #646
Opened 2023-04-05 19:20 UTC by Dario-Felipe

## Description 📄

- It was added a new prop to `<Tag />` component, called `ellipsis`, that will work together `maxWidth` prop to put, if needs, some ellipsis for large texts.
- With this feature the`<Tag />` component start to accept maxWidth prop too;

 This issue was looked by vms team, because one of ours features needs Tag component and some texts are too large, so was needed put ellipsis to hide their.

## Platforms 📲

- [x] Web
- [ ] Mobile

## Type of change 🔍

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? 🧪

- [ ] Unit Test
- [x] Snapshot Test

## Checklist: 🔍

- [x] My code follows the contribution guide of this project [Contributing Guide](https://github.com/Gympass/yoga/blob/master/CONTRIBUTING.md)
- [ ] Layout matches design prototype: [FIGMA](https://figma.com/file/YOUR_LINK)
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Screenshots 📸

Default Tag:

![image](https://user-images.githubusercontent.com/59899974/230179689-f3138363-6ac2-4dc0-a710-8c55f3e8c33c.png)

Informative Tag:

![image](https://user-images.githubusercontent.com/59899974/230179505-ce8e3e43-766a-4125-aa8b-2dc82190f12a.png)

2023-04-06 07:06 UTC, tomaskeong requested changes

2023-04-06 07:06 UTC, tomaskeong commented on packages/doc/content/components/components/tag/default-web.mdx
> +The tag component can recieve a ellipsis prop that will put a ellipsis (...) if is a large text.
```suggestion
The tag component can receive an ellipsis prop that will add "..." if is a large text.
```

2023-04-10 16:48 UTC, wellingtonnascimento approved these changes

2023-04-11 12:14 UTC, matheushdsbr approved these changes

2023-04-11 12:29 UTC, tomaskeong approved these changes

2023-04-11 12:39 UTC, merged