Feat/navigation menu
gympass/yoga pull request #692
Opened 2023-09-26 08:56 UTC by lsantos1873

[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/PPE-384)

## Description 📄

This PR adds the Navigation Menu component.

## Platforms 📲

- [x] Web
- [ ] Mobile

## Type of change 🔍

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? 🧪

[Enter the tips to test this PR]

- [ ] Unit Test
- [x] Snapshot Test

## Checklist: 🔍

- [ ] My code follows the contribution guide of this project [Contributing Guide](https://github.com/Gympass/yoga/blob/master/CONTRIBUTING.md)
- [ ] Layout matches design prototype: [FIGMA](https://figma.com/file/YOUR_LINK)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Screenshots 📸

#### Navigation menu
![image](https://github.com/gympass/yoga/assets/32453477/d4470c0c-32af-4c9f-842c-c5db9afdf5a1)

#### Menu subcomponent with an action
![image](https://github.com/gympass/yoga/assets/32453477/63870cc7-7574-45bb-8234-0e3129a25693)

#### Switcher subcomponent with actions
![image](https://github.com/gympass/yoga/assets/32453477/63c1dc52-4d7a-4a3f-8df1-7d1f77e8ffeb)

2023-09-26 10:05 UTC, lsantos1873 commented on tsconfig.json
> +    "jsx": "react-jsx"
@matheushdsbr I believe this configuration "jsx": "react-jsx" should be added as well to your PR.

2023-10-11 12:26 UTC, MicaelRodrigues approved these changes
LGTM, just confirmed building with TS + js still works

2023-10-18 13:39 UTC, luanlorenzo approved these changes

2023-10-31 17:30 UTC, matheushdsbr requested changes

2023-10-31 17:30 UTC, matheushdsbr commented on packages/yoga/src/NavigationMenu/web/NavigationMenu.styles.ts
Thank you, @lsantos1873 , for your contribution! 
This will greatly improve our project when incorporating components with TypeScript. 🚀

We need to make some changes to address the errors that are currently affecting the build process.

To begin with, it is crucial to refactor the style file to follow the Yoga component pattern by introducing a corresponding theme file. A great example of this pattern is the Button component, which features a Button.theme.js file that can serve as a valuable reference.

First you can remove `NavigationMenu.styles.ts` and add `NavigationMenu.theme.ts` like this::

```
const NavigationMenu = ({
   spacing,
   colors,
}) => ({
   colors: {
     clear: colors.clear,
   },
   gap: {
     medium: spacing.medium,
     xxxsmall: spacing.xxxsmall,
   },
   padding: {
     small: spacing.small,
     xsmall: spacing.xsmall,
   },
});

export default NavigationMenu;`
```

Right now, our theme files only recognize `**.theme.js` files. I'm considering a potential solution to enable them to work with TypeScript (`**.theme.ts`) files as well:

path:`yoga/packages/yoga/src/Theme/theme/theme.js`
```
...
import * as componentThemesJS from '../../**/*.theme.js';
import * as componentThemesTS from '../../**/*.theme.ts';

const getComponentThemes = tokens => {
   const componentThemes = { ...componentThemesJS, ...componentThemesTS };
...
```

So you can then use this in your NavigationMenu.tsx as follows:

```
export const NavigationMenuStyled = styled(Box)<NavigationMenuProps>`
  ...
   ${({
     theme: {
       yoga: {
         components: { navigationmenu },
       },
     },
   }) => {
     return `
     gap: ${navigationmenu.gap.medium}px;
     padding: ${navigationmenu.padding.small}px ${navigationmenu.padding.xsmall}px;
     background-color: ${navigationmenu.colors.clear};
     `;
   }}
...
`;
```

Subsequently, you can integrate this structure into your NavigationMenu.tsx, like so:

```
export const NavigationMenuStyled = styled(Box)<NavigationMenuProps>`
  ...
   ${({
     theme: {
       yoga: {
         components: { navigationmenu },
       },
     },
   }) => {
     return `
     gap: ${navigationmenu.gap.medium}px;
     padding: ${navigationmenu.padding.small}px ${navigationmenu.padding.xsmall}px;
     background-color: ${navigationmenu.colors.clear};
     `;
   }}
...
```

These styling definitions should reside within the component file itself, in this case, `NavigationMenu.tsx`. 

By consistently applying this pattern to all created components referred to Navigation Menu, you should be able to resolve typing errors related to the theme. With this way we won't need the `yoga.d.ts` file.

2023-11-15 11:41 UTC, lsantos1873 commented on packages/yoga/src/NavigationMenu/web/NavigationMenu.styles.ts
Thanks @matheushdsbr for the suggestions. I have refactored all the styles according to your suggestions and yoga pattern. Please have a look.

2023-12-18 17:20 UTC, merged