[DS-782] Add antialiased for Font-Weight issues
gympass/yoga pull request #744
Opened 2024-03-01 17:02 UTC by evilamaior

[![JIRA Issue](https://img.shields.io/badge/issue-JIRA-blue.svg)](https://gympass.atlassian.net/browse/DS-782)

## Description 📄

- DS-782

## Platforms 📲

- [x] Web
- [ ] Mobile

## Type of change 🔍

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? 🧪

[Enter the tips to test this PR]

- [x] Unit Test
- [ ] Snapshot Test

## Checklist: 🔍

- [ ] My code follows the contribution guide of this project [Contributing Guide](https://github.com/Gympass/yoga/blob/master/CONTRIBUTING.md)
- [ ] Layout matches design prototype: [FIGMA](https://figma.com/file/YOUR_LINK)
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Screenshots 📸

[Upload your screenshots here]

| Before | After |
| ------ | ----- |
|        |       |

2024-03-04 12:15 UTC, tcK1 requested changes

2024-03-04 12:15 UTC, tcK1 commented on packages/yoga/src/Theme/theme/v3theme.ts
>    },
I think we can remove this property. 💡

2024-03-04 17:53 UTC, evilamaior commented on packages/yoga/src/Theme/theme/v3theme.ts
>    },
Thanks, done!

2024-03-04 18:14 UTC, flavia-moraes approved these changes

2024-03-05 12:47 UTC, matheushdsbr approved these changes

2024-03-05 17:18 UTC, merged